---
# Toggle which domain lists are appended into the final domains.lst
domains_copilot: true
domains_google: true
domains_instagram: true
domains_netflix: true
domains_telegram: false
domains_datadog: true

domains_local_lists:
  - name: copilot.lst
    enabled: "{{ domains_copilot }}"
  - name: datadog.lst
    enabled: "{{ domains_datadog }}"
  - name: google.lst
    enabled: "{{ domains_google }}"
  - name: instagram.lst
    enabled: "{{ domains_instagram }}"
  - name: netflix.lst
    enabled: "{{ domains_netflix }}"
  - name: telegram.lst
    enabled: "{{ domains_telegram }}"
