---
wifi_devices:
  - index: 0
    enabled: true
  - index: 1
    enabled: true

wifi_ifaces:
  - index: 0
    enabled: true
    options:
      - option: ssid
        value: 'NetworkName_2G'
      - option: encryption
        value: 'psk2'
      - option: key
        value: 'Password2G'
  - index: 1
    enabled: true
    options:
      - option: ssid
        value: 'NetworkName_5G'
      - option: encryption
        value: 'psk2'
      - option: key
        value: 'Password5G'
