---
# handlers file for router role

- name: Reload dnsmasq
  ansible.builtin.command:
    cmd: /etc/init.d/dnsmasq reload
  changed_when: true

- name: Reload firewall
  ansible.builtin.command:
    cmd: /etc/init.d/firewall reload
  changed_when: true

- name: Restart sing-box
  ansible.builtin.command:
    cmd: /etc/init.d/sing-box restart
  changed_when: true

- name: Commit and reload WiFi
  ansible.builtin.command:
    cmd: uci commit wireless && wifi reload
  changed_when: true
